/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sketchfab (https://sketchfab.com/Sketchfab)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/plane-f2615549f73946baa65d35fbcf9ee884
title: Sketchfab 5 Million Members
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model() {
  const { nodes, materials } = useGLTF('assets/gltfs/plane/scene.gltf');
  const propellerRef = useRef(null);
  const planeRef = useRef(null);
  const modelRef = useRef(null);

  let frameCounter = 0;
  useFrame(() => {
    frameCounter++;
    propellerRef.current.rotateX(0.10)
    
    
  
 
     if (frameCounter <= 200) {
       planeRef.current.rotateX(0.002)
     }
     if (frameCounter > 100) {
       planeRef.current.rotateX(-0.002)
     }
     if (frameCounter === 300) {
       frameCounter = 0
     }
     
     
    modelRef.current.position.x -= 0.03
  })



  return (
    <group rotation={[0, 0, 0]} ref={modelRef} position={[3.8, 0, 8]} scale={3}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.07}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.95, -0.25, -0.06]} rotation={[1.56, -0.03, 0.01]}>
            <group position={[3.2, 0.08, 0.07]} rotation={[-2.92, -1.55, -2.9]}>
              <primitive object={nodes.GLTF_created_0_rootJoint} />
              <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.Bits} skeleton={nodes.Object_31.skeleton} />
            </group>
            <mesh geometry={nodes.Object_33.geometry} material={materials.Bits} />
          </group>
          <group ref={planeRef} >
            <group position={[-39.95, 0, -5.27]} scale={0}>
              <mesh geometry={nodes.Object_4.geometry} material={materials.Wind} />
            </group>
            <group position={[-39.95, 4.09, 0]} scale={0}>
              <mesh geometry={nodes.Object_6.geometry} material={materials.Wind} />
            </group>
            <group position={[-39.94, -2.72, 2.36]} scale={0}>
              <mesh geometry={nodes.Object_8.geometry} material={materials.Wind} />
            </group>
            <group ref={propellerRef} position={[-2.43, -0.01, 0]} rotation={[2.09, 0, 0]}>
              <mesh geometry={nodes.Object_11.geometry} material={materials.Bits} />
              <mesh geometry={nodes.Object_13.geometry} material={materials.Wind} />
            </group>
            <group rotation={[1.57, 0, 0]}>
              <group position={[-0.72, 0, -0.04]}>
                <mesh geometry={nodes.Object_38.geometry} material={materials.Bits} />
                <mesh geometry={nodes.Object_40.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_42.geometry} material={materials.Window} />
                <mesh geometry={nodes.Object_45.geometry} material={materials.Bits} />
                <mesh geometry={nodes.Object_48.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_50.geometry} material={materials.Wind} />
                <mesh geometry={nodes.Object_53.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_55.geometry} material={materials.Wind} />
              </group>
            </group>
            <group position={[2.08, 0.53, -0.01]} rotation={[1.57, 0, 0.01]}>
              <mesh geometry={nodes.Object_58.geometry} material={materials.Body} />
            </group>
            <group position={[-0.66, 0.96, -1.85]} rotation={[1.57, 0.01, 0]}>
              <mesh geometry={nodes.Object_61.geometry} material={materials.Bits} />
              <mesh geometry={nodes.Object_63.geometry} material={materials.Wind} />
            </group>
            <group position={[-0.66, 0.97, 1.84]} rotation={[1.57, 0, 0]}>
              <mesh geometry={nodes.Object_66.geometry} material={materials.Bits} />
              <mesh geometry={nodes.Object_68.geometry} material={materials.Wind} />
            </group>
            <group position={[-39.87, -2.23, -18.55]} scale={0}>
              <mesh geometry={nodes.Object_70.geometry} material={materials.Clouds} />
            </group>
            <group position={[-40.88, 13.85, 18.8]} scale={0}>
              <mesh geometry={nodes.Object_72.geometry} material={materials.Clouds} />
            </group>
            <group position={[-39.95, -21.13, -0.64]} scale={0}>
              <mesh geometry={nodes.Object_74.geometry} material={materials.Clouds} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('assets/gltfs/plane/scene.gltf')
